// <auto-generated />
using AdvancedRag.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AdvancedRag.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260520170000_RenameLegacyContentStorageToDocuments")]
partial class RenameLegacyContentStorageToDocuments
{
}
