"""v2: add multi-turn session and filter audit fields

This migration is part of the v2 generic refactor. See:
- docs/adr/0002-hybrid-retrieval.md (rerank/bm25/vector top_k fields)
- docs/adr/0009-conversational-memory.md (session_id, rewritten_question)
- docs/v2/03-phases.md (Phase 5.2 + 2.4)

Adds to `rag.query_audit_events`:
- `session_id` UUID — groups multi-turn messages
- `previous_event_id` UUID FK — links to the prior turn in the same session
- `rewritten_question` TEXT — standalone question generated by the condensation step
- `filters` JSONB — pre-applied dimension filters from the client
- `vector_top_k`, `bm25_top_k`, `rerank_top_k` INT — retrieval pipeline params
- `reranker_model` TEXT, `reranker_score` NUMERIC — top reranker score for the answer
- `api_key_id` UUID — set when the request was authenticated by an API key, not a session
- `filters_hash` TEXT — short hash used as part of the cache partition key
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "20260522_120200"
down_revision: str | None = "20260522_120100"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        """
        ALTER TABLE rag.query_audit_events
            ADD COLUMN session_id uuid,
            ADD COLUMN previous_event_id uuid REFERENCES rag.query_audit_events(id),
            ADD COLUMN rewritten_question text,
            ADD COLUMN filters jsonb,
            ADD COLUMN filters_hash text,
            ADD COLUMN vector_top_k int,
            ADD COLUMN bm25_top_k int,
            ADD COLUMN rerank_top_k int,
            ADD COLUMN reranker_model text,
            ADD COLUMN reranker_score numeric(6, 4),
            ADD COLUMN api_key_id uuid;
        """
    )

    op.execute(
        """
        CREATE INDEX ix_query_audit_session
            ON rag.query_audit_events (session_id, created_at DESC)
            WHERE session_id IS NOT NULL;
        """
    )

    op.execute(
        """
        CREATE INDEX ix_query_audit_filters_hash
            ON rag.query_audit_events (corpus, access_scope_hash, filters_hash)
            WHERE filters_hash IS NOT NULL;
        """
    )

    # Also enrich the semantic cache key to include filters.
    op.execute(
        """
        ALTER TABLE rag.semantic_cache_entries
            ADD COLUMN filters_hash text;
        """
    )

    op.execute(
        """
        CREATE INDEX ix_semantic_cache_corpus_scope_filters
            ON rag.semantic_cache_entries (corpus, access_scope_hash, filters_hash)
            WHERE filters_hash IS NOT NULL;
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS rag.ix_semantic_cache_corpus_scope_filters;")
    op.execute(
        """
        ALTER TABLE rag.semantic_cache_entries DROP COLUMN IF EXISTS filters_hash;
        """
    )
    op.execute("DROP INDEX IF EXISTS rag.ix_query_audit_session;")
    op.execute("DROP INDEX IF EXISTS rag.ix_query_audit_filters_hash;")
    op.execute(
        """
        ALTER TABLE rag.query_audit_events
            DROP COLUMN IF EXISTS api_key_id,
            DROP COLUMN IF EXISTS reranker_score,
            DROP COLUMN IF EXISTS reranker_model,
            DROP COLUMN IF EXISTS rerank_top_k,
            DROP COLUMN IF EXISTS bm25_top_k,
            DROP COLUMN IF EXISTS vector_top_k,
            DROP COLUMN IF EXISTS filters_hash,
            DROP COLUMN IF EXISTS filters,
            DROP COLUMN IF EXISTS rewritten_question,
            DROP COLUMN IF EXISTS previous_event_id,
            DROP COLUMN IF EXISTS session_id;
        """
    )
