services:
  postgres:
    ports:
      - "5432:5432"

  minio:
    ports:
      - "127.0.0.1:9001:9001"

  dotnet-api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  rag-api:
    environment:
      APP_ENV: development

  caddy:
    environment:
      PUBLIC_DOMAIN: localhost
